server:
  port: 9999

#数据源
spring:
  datasource:
    url: jdbc:mysql://101.37.17.194:3306/asset?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

pagehelper:
  helper-dialect: mysql

#打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
